### ISSUE TITLE
Error: Class 'App\View\Helper\ComponentCollection' not found 

### ISSUE THREAD

**Issue by jkimilu** [shahonseven/CakePHP-Acl-Link-Helper#3]
Hi ,

Am using cakephp3.2, trying to integrate with acllinkhelper but am getting below error,
Error: Class 'App\View\Helper\ComponentCollection' not found 
Please help

Regards

**Comment by shahonseven** [comment]
hi,

please use this version https://github.com/shahonseven/CakePHP-AclLinkHelper/tree/3.x
