### ISSUE TITLE
Poslink

### ISSUE THREAD

**Issue by jkimilu** [shahonseven/CakePHP-Acl-Link-Helper#4]
Declaration of App\View\Helper\AclLinkHelper::postLink() should be compatible with Cake\View\Helper\FormHelper::postLink($title, $url = NULL, array $options = Array) [APP/View/Helper/AclLinkHelper.php, line 16

Kindly help solve above error, #cakephp3.2

**Comment by shahonseven** [comment]
Hi, please use this version https://github.com/shahonseven/CakePHP-AclLinkHelper/tree/3.x

**Comment by jkimilu** [comment]
Thank you. Sir works like charm

Thanks
